### ISSUE TITLE
Compile failure - missing LV2_UI__scaleFactor

### ISSUE THREAD

**Issue by Rippert** [brummer10/Rumor#1]
Hey Hermann, I tried to compile Rumor, but it spit out this error:
```
In file included from Rumor.c:74:
lv2_plugin.cc: In function ‘instantiate’:
lv2_plugin.cc:362:71: error: ‘LV2_UI__scaleFactor’ undeclared (first use in this function); did you mean ‘ui_scaleFactor’?
         const LV2_URID ui_scaleFactor = ui->map->map(ui->map->handle, LV2_UI__scaleFactor);
                                                                       ^~~~~~~~~~~~~~~~~~~
                                                                       ui_scaleFactor
lv2_plugin.cc:362:71: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [makefile:104: Rumor] Error 1
make[1]: Leaving directory '/home/tedrippert/src/Rumor/Rumor'
make: *** [makefile:27: Rumor] Error 2
```
I do have  libX11-dev 2:1.6.7  and libcairo2-dev 1.6.7 installed.

**Comment by brummer10** [comment]
Hi @Rippert 
You need LV2 1.18.0 for that.
regards
hermann

**Comment by brummer10** [comment]
Hi @Rippert 
Okay, I've implemented a fix for that, so you don't been forced to update your lv2 stack.

**Comment by Rippert** [comment]
Thanks Hermann. That worked fine. My distribution only goes up to 1.14 on lv2-dev.

Sounds very nice on my big speakers. Lots of bottom end with the intensity at 0, but still very nice growl to it. Gets really nasty at higher intensity, which is good for when it's needed.

Thanks.
